'use strict';

const fs = require('fs/promises');
const path = require('path');
const crypto = require('crypto');

const DATA_DIR = process.env.DATA_DIR || path.join(__dirname, 'data');
const TTL_DAYS = parseFloat(process.env.TTL_DAYS || '30');

async function ensureDataDir() {
    await fs.mkdir(DATA_DIR, { recursive: true });
}

function newId() {
    // URL-safe, 10 chars, ~59 bits of entropy — enough that share links aren't guessable
    return crypto.randomBytes(8).toString('base64url').slice(0, 11);
}

function newDeleteToken() {
    return crypto.randomBytes(24).toString('base64url');
}

function hashToken(token) {
    return crypto.createHash('sha256').update(token).digest('hex');
}

function recordPath(id) {
    // id is generated by us (base64url, no path separators) but validate anyway
    // before it ever touches the filesystem.
    if (!/^[A-Za-z0-9_-]{6,32}$/.test(id)) throw new Error('invalid id');
    return path.join(DATA_DIR, id + '.json');
}

async function create(reportJson) {
    await ensureDataDir();
    const id = newId();
    const deleteToken = newDeleteToken();
    const now = Date.now();
    const record = {
        id,
        createdAt: now,
        expiresAt: now + TTL_DAYS * 24 * 60 * 60 * 1000,
        deleteTokenHash: hashToken(deleteToken),
        report: reportJson,
    };
    await fs.writeFile(recordPath(id), JSON.stringify(record), 'utf8');
    return { id, deleteToken, expiresAt: record.expiresAt };
}

async function get(id) {
    let raw;
    try {
        raw = await fs.readFile(recordPath(id), 'utf8');
    } catch (e) {
        if (e.code === 'ENOENT') return null;
        throw e;
    }
    const record = JSON.parse(raw);
    if (record.expiresAt < Date.now()) {
        await fs.unlink(recordPath(id)).catch(() => {});
        return null;
    }
    return record;
}

async function remove(id, deleteToken) {
    const record = await get(id);
    if (!record) return { ok: false, reason: 'not_found' };
    const providedHash = hashToken(deleteToken || '');
    const expectedHash = record.deleteTokenHash;
    const a = Buffer.from(providedHash, 'hex');
    const b = Buffer.from(expectedHash, 'hex');
    if (a.length !== b.length || !crypto.timingSafeEqual(a, b)) {
        return { ok: false, reason: 'bad_token' };
    }
    await fs.unlink(recordPath(id)).catch(() => {});
    return { ok: true };
}

async function cleanupExpired() {
    await ensureDataDir();
    const files = await fs.readdir(DATA_DIR).catch(() => []);
    const now = Date.now();
    let removed = 0;
    for (const f of files) {
        if (!f.endsWith('.json')) continue;
        const p = path.join(DATA_DIR, f);
        try {
            const raw = await fs.readFile(p, 'utf8');
            const record = JSON.parse(raw);
            if (record.expiresAt < now) {
                await fs.unlink(p);
                removed++;
            }
        } catch (_) { /* skip unreadable/corrupt entries */ }
    }
    return removed;
}

module.exports = { create, get, remove, cleanupExpired, DATA_DIR, TTL_DAYS };
